final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nikes',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '1',
    'title': 'Men\'s Nike Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Women\'s Adidas Shoes',
    'price': 22.95,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '3',
    'title': 'Men\'s Bata Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Bata',
    'sizes': [8, 9, 10, 12],
  },
  {
    'id': '4',
    'title': 'Women\'s Puma Shoes',
    'price': 59.90,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Puma',
    'sizes': [9, 10, 11],
  },
  {
    'id': '6',
    'title': 'Men\'s Puma Shoes',
    'price': 69.95,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Puma',
    'sizes': [9, 10, 11, 12],
  },
];
